### ISSUE TITLE
PackageDownloadLocations are in incorrect format

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-examples#27]
Currently, the `PackageDownloadLocation` examples are in the format given by GitHub for SSH access, e.g. for example5:

```
PackageDownloadLocation: git@github.com:swinslow/spdx-examples.git#example5/content/src
```

However, this is incorrect according to [the SPDX 2.2 spec](https://spdx.github.io/spdx-spec/3-package-information/#37-package-download-location). I'm not certain I follow how to represent the SSH access version (or if it's even possible to do so), but it looks like it should be done via HTTPS instead, e.g.:

```
PackageDownloadLocation: git+https://github.com/swinslow/spdx-examples.git#example5/content/src
```

The examples should be updated to fix this error, as they won't parse correctly in the current form.

**Comment by goneall** [comment]
This is now fully fixed
