### ISSUE TITLE
Add examples in all supported formats

### ISSUE THREAD

**Issue by zkajzer** [spdx/spdx-examples#41]
As per the [documentation](https://spdx.dev/resources/use/#documents), SPDX Documents can be in one of the following formats: _tag/value (.spdx), JSON(.spdx.json), YAML(.spdx.yml), RDF/xml(spdx.rdf) and spreadsheets (.xls)._

Currently there are only tag/value and JSON examples in the repo.

I tried to use this repo to find examples because I am integrating the [Spdx-Java-Library](https://github.com/spdx/Spdx-Java-Library) into my project, and would need to use files in all formats for testing purposes.

**Comment by swinslow** [comment]
Hi @zkajzer, thanks for reaching out!

One place where you can find examples in all supported formats is in the main SPDX specification repo: https://github.com/spdx/spdx-spec/tree/development/v2.2.2/examples

The examples there should be equivalent to one another, expressed in the various serialization formats.

For this spdx-examples repo, my goal was to have several sets of much simpler examples of SPDX documents for various use cases. I'd welcome contributions (from you or others in the SPDX community) of documents in the other formats to sit alongside the tag-value and JSON documents that we've currently got here.

**Comment by goneall** [comment]
Since this is covered in the spec examples and we [updated the README file to point to this](https://github.com/spdx/spdx-examples/blob/6c6a6c11a66d91b63b15ad252837b7cc8714e44d/README.md?plain=1#L5C1-L5C1), I'm closing this issue as resolved.
