### ISSUE TITLE
Invalid Download location

### ISSUE THREAD

**Issue by dangerousHobo** [spdx/spdx-examples#42]
Looking at the examples for Go I noticed they used a syntax what is not mentioned in the SPDX spec:
https://spdx.github.io/spdx-spec/package-information/#77-package-download-location-field

https://github.com/spdx/spdx-examples/blob/7b78ca07e64490cff7817593b9fa83c35db59dd7/example7/spdx/example7-third-party-modules.spdx.json#L24

Is this a valid entry for the Download Location field? If so, can I be pointed to the appropriate section of the spec. If not, is this something that is planned in a draft of an upcoming revision?

**Comment by goneall** [comment]
Fixed in PR #66
