### ISSUE TITLE
JSON encoding should use boolean values for booleans

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-examples#44]
Files `example7-bin.spdx.json`, `example7-go-module.spdx.json`, and `example7-golang.spdx.json` (lines 24 and 40) have property
```json
"filesAnalyzed": "false"
```
Boolean types should have JSON Boolean values (`"filesAnalyzed": false`), not string values.

**Comment by goneall** [comment]
It looks like this has been fixed in a previous PR
