### ISSUE TITLE
Invalid SPDXIDs in example10 and example 8

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-examples#54]
The files in `example8/` and `example10/` contain invalid `SPDXIDs`. 

In  [examplemaven-0.0.1.spdx.json ](https://github.com/spdx/spdx-examples/blob/master/example8/spdx/examplemaven-0.0.1.spdx.json) there are some typos where the packages `SPDXID` start with `SPDXREf-..` instead of `SPDXRef-..`. 
- Affected packages: 
  * SPDXREf-log4jslf4jbinding
  * SPDXREf-log4jslf4jApi
  * SPDXREf-log4jApi
  * SPDXREf-log4jImpl
  * SPDXREf-example

In [hello-source.spdx.json](https://github.com/spdx/spdx-examples/blob/master/example10/spdx/hello-source.spdx.json) the document `SPDXID` is lowercase `SPDXRef-Document` instead of uppercase `SPDXRef-DOCUMENT` as described in the [spec](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#63-spdx-identifier-field).

**Comment by goneall** [comment]
Example 8 has been fixed with PR #55
