### ISSUE TITLE
Example 7 does not match the schema

### ISSUE THREAD

**Issue by elear** [spdx/spdx-examples#62]
[Example 7](https://github.com/spdx/spdx-examples/blob/master/example7/spdx/example7-golang.spdx.json) is not well formed SPDX because PackageName is not defined in the [schema](https://github.com/spdx/spdx-spec/blob/master/schemas/spdx-schema.json). That should simply be "name".  That is one of many errors with that example.  I think it's the same with anything that begins with "Package".

**Comment by goneall** [comment]
Fixed with PR #66
