### ISSUE TITLE
Proposal: Include use case persona and profile information in the examples

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-examples#65]
Since SPDX covers many different use cases with several different stakeholders, it would help to organize the examples so that someone interested in a specific set of use cases can find the examples easily.

For example, someone interested in security may not be interested in the licensing profiles and visa-versa.

I would propose creating separate directories for each of the profiles.

The current examples are more "Software" oriented and covers the area of how different types of artifacts would be represented - I would propose moving all of the examples under Software.

We could create a separate README for each directory which summarizes the examples.

The top level README could point to the different directories and summarize the profile.

**Comment by goneall** [comment]
@nishakm @puerco @swinslow @ivanayov As past contributors to this repo - let me know what you think.  If you agree with this approach, I'll create the PR.

**Comment by nishakm** [comment]
@goneall do you think it makes more sense to move the current examples to a top level `spdx2.2` directory rather than keep each example directory and create a folder within called `spdx3.0/security` or something like that?

**Comment by goneall** [comment]
> do you think it makes more sense to move the current examples to a top level spdx2.2 directory rather than keep each example directory and create a folder within called spdx3.0/security or something like that?

I'm thinking I'll add SPDX 3.0 examples for all of the the current SPDX 2.2 examples - running it through the Java tools conversion.  Once that's done, I think it would make more sense to organize the top level by persona and then by spec version.  I'm thinking folks will come to the repo with a specific use case in mind in which case they will see it at the top level.

**Comment by ivanayov** [comment]
+1 from me :) Will be easier to refer to with SPDX 3.0.

**Comment by swinslow** [comment]
+1, sounds good to me!

**Comment by goneall** [comment]
Resolved with #72
